
"""
ERRORS
"""
SERVER_ERROR = "SERVER_ERROR"
CLIENT_ERROR = "CLIENT_ERROR"
ERROR = "ERROR"
"""
commands
"""
AUTHENTICATE_CONNECTION = "AUTHENTICATE_CONNECTION"
HEARTBEAT = "HEARTBEAT"
JOIN_ROOM = "JOIN_ROOM"
LEAVE_ROOM = "LEAVE_ROOM"
