# Generated by Django 2.2.3 on 2019-09-07 03:23

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='data',
        ),
        migrations.RemoveField(
            model_name='room',
            name='state',
        ),
        migrations.AddField(
            model_name='room',
            name='game_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='room',
            name='game_type',
            field=models.CharField(choices=[('TR', 'TRIVIA')], default='TR', max_length=2),
        ),
        migrations.AddField(
            model_name='room',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='All Welcome', max_length=30),
        ),
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SocketTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
