

SERVER_ERROR = "SERVER_ERROR"
CLIENT_ERROR = "CLIENT_ERROR"

"""
commands
"""
VALIDATE_CONNECTION = "VALIDATE_CONNECTION"
JOIN_ROOM = "JOIN_ROOM"
LEAVE_ROOM = "LEAVE_ROOM"
UPDATE_ROOM = "UPDATE_ROOM"
